sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
# whitelist
branches:
  only:
    - master
    - develop
node_js:
  - iojs
before_install:
  - npm i -g jshint
